import type { CSSProperties } from "react";
import { ASSETS } from "@/lib/asset-manifest";

export type Ratio = "1:1" | "4:5" | "3:4" | "4:3" | "3:2" | "16:9";

const RATIO_CLASS: Record<Ratio, string> = {
  "1:1": "ratio-1-1",
  "4:5": "ratio-4-5",
  "3:4": "ratio-3-4",
  "4:3": "ratio-4-3",
  "3:2": "ratio-3-2",
  "16:9": "ratio-16-9",
};

type Props = {
  /** MEDIA.md row id, e.g. "M09". Printed in the tag so a mismatch is visible. */
  id: string;
  /** exact target path under public/. This IS the filename Stage 4 must write. */
  path: string;
  type?: "image" | "video";
  ratio: Ratio;
  /** short human brief. The full prompt lives in MEDIA.md. */
  brief: string;
  className?: string;
  style?: CSSProperties;
};

/**
 * Media slot, gated on the real filesystem.
 *
 * R15, the rule this component exists to make unbreakable: nothing here ever
 * points a `<video src>` or a `<source src>` at a file that is not on disk. A
 * `<video>` wired to a missing mp4 renders a frozen poster and reads as a
 * broken hero, which is exactly how dapur-tepat, portfolio-kilau,
 * gunung-rezeki, and sinyalkita shipped dead heroes.
 *
 * `ASSETS` (`src/lib/asset-manifest.ts`) is generated by
 * `scripts/gen-asset-manifest.mjs` from what actually exists under `public/`
 * at build time, so the check below is a real per-asset filesystem gate, not
 * a guess from the data model. Present on disk: real `<img>`/`<video>`.
 * Absent: the honest annotated placeholder, never a broken src.
 */
export default function Media({
  id,
  path,
  type = "image",
  ratio,
  brief,
  className = "",
  style,
}: Props) {
  const exists = Boolean(ASSETS[path]);

  if (!exists) {
    return (
      <div
        className={`ph ${RATIO_CLASS[ratio]} ${className}`.trim()}
        style={style}
        data-media={path}
        data-type={type}
        data-ratio={ratio}
        data-media-id={id}
        role="img"
        aria-label={brief}
      >
        <span className="ph-tag">
          [MEDIA {id}] {brief} Rasio {ratio}.
        </span>
      </div>
    );
  }

  const src = `/${path}`;

  if (type === "video") {
    return (
      <video
        className={`media-real ${RATIO_CLASS[ratio]} ${className}`.trim()}
        style={style}
        data-media={path}
        data-type={type}
        data-ratio={ratio}
        data-media-id={id}
        aria-label={brief}
        autoPlay
        muted
        loop
        playsInline
        preload="auto"
      >
        <source src={src} type="video/mp4" />
      </video>
    );
  }

  return (
    <img
      className={`media-real ${RATIO_CLASS[ratio]} ${className}`.trim()}
      style={style}
      data-media={path}
      data-type={type}
      data-ratio={ratio}
      data-media-id={id}
      src={src}
      alt={brief}
      loading="lazy"
    />
  );
}
